name: 'merchant_iq_analytics'
version: '1.0.0'
config-version: 2
profile: 'merchant_iq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  merchant_iq_analytics:
    marts:
      +materialized: table
    staging:
      +materialized: view
